[server]
host = "localhost"
port = 40400
http-port = 40402
metrics-port = 40403
no-upnp = true
default-timeout = 2000
#bootstrap = "rnode://de6eed5d00cf080fc587eeb412cb31a75fd10358@52.119.8.109:40400"
standalone = true
#data-dir = "."
map-size = 1073741824
casper-block-store-size = 1073741824
in-memory-store = false
max-num-of-connections = 500
[grpc-server]
host = "localhost"
port = 40401
port-internal = 40404
[tls]
#certificate = "/var/lib/rnode/certificate.pem"
#key = "/var/lib/rnode/key.pem"
[validators]
count = 5
shard-id = "rchain"
sig-algorithm = "ed25519"
#bonds-file = "./genesis/bonds.txt"
# wallets-file = ""
# known = ""
# public-key = "" # Inferred from private key
# WARNING!! Do not commit REAL private keys EVER. We'll stop doing this when it becomes practicable.
private-key = "9d6060a868e43dd862bc65ab1acc657c9b5234906c8b94fe253f1a6f9908524e"
# For sk files
# filename -> public key
# contents -> secret key
